### ISSUE TITLE
Seq> 1 for train_singlenet_phase_1fc 

### ISSUE THREAD

**Issue by nisargshah1999** [YuemingJin/TMRNet#4]
Hi,
Thanks for the interesting code
When I run train_singlenet_phase_1fctrain_singlenet_phase_1fc.py in Training memory bank, the inputs doesn't have seq frames, only one frame
Seems, some issue with data-loader
For eg, for seq = 10,

I am getting below mentioned error
```
Traceback (most recent call last):
  File "/home/nisarg/Downloads/research/cataract/code/TMRNet/code/Training memory bank model/train_singlenet_phase_1fc.py", line 681, in <module>
    main()
  File "/home/nisarg/Downloads/research/cataract/code/TMRNet/code/Training memory bank model/train_singlenet_phase_1fc.py", line 674, in main
    train_model((train_dataset_80),
  File "/home/nisarg/Downloads/research/cataract/code/TMRNet/code/Training memory bank model/train_singlenet_phase_1fc.py", line 494, in train_model
    inputs = inputs.view(-1, sequence_length, 3, 224, 224)
RuntimeError: shape '[-1, 10, 3, 224, 224]' is invalid for input of size 150528
```

**Comment by YonghaoLong** [comment]
Hi,

I think it's due to the batch size. You have to make sure the size is in multiples of 10 (sequence_length).
